#!/data/data/com.termux/files/usr/bin/bash

#---------------------------------------------------------$
#"THE BEER-WARE LICENSE" (Revision 42):
#<Buka> wrote this file.  As long as you
#retain this notice you can do whatever you want with
#this stuff. If we meet some day, and you think this
#stuff is worth it, you can buy me a beer in return.
#Buka
#---------------------------------------------------------$

########################
#Default Variables
########################

shopt -s extglob

folderIcon="📂"
otherIcon="📜"
upDirIcon="🔙"
actionIcon="✅"
archiveIcon="📦"

packageList="sed gawk jq tar bsdtar zip unzip p7zip cpio xz-utils lzip bzip2 gzip"

binList="sed awk tar jq bsdtar zip unzip 7z cpio xz lzip bzip2 gzip"

dictSizes="1m,2m,4m,8m,16m,32m,64m,128m,256m,512m,1024m"

archiveTypes=".zip|.7z|.iso|.gz|.bz2|.xz|.lz|.rar|.jar|.apk|.tar|.001|.tgz|.tbz2|.txz|.tlz|.lzma|.t7z"

########################
#Functions
########################

getSelection(){
    selection="$(jq -r '.text' <<< "$1")"
}

getExCode(){
    excode="$(jq -r '.code' <<< "$1")"
    if [[ ! "$excode" == "$2" ]]
    then
        exit 0
    fi
}
buildListing(){
    if [[ "$1" == "dirs" ]]
    then
        listing="$(ls -d .*/ */ | cut -f1 -d'/' | tail -n+3)"
    else
        listing="$(ls -A --group-directories-first)"
    fi
    for kv in $listing
    do
        if [[ -z "$dirList" ]]
        then
            delSym=''
        else
            delSym=','
        fi
        if [[ -f "$kv" ]]
        then
            if [[ "$kv" =~ (${archiveTypes})$ ]]
            then
                fileIcon="$archiveIcon"
            else
                fileIcon="$otherIcon"
            fi
            dirList="${dirList}${delSym}${fileIcon} ${kv}"
        elif [[ -d "$kv" ]]
        then
            dirList="${dirList}${delSym}${folderIcon} ${kv}"
        fi
    done
}
buildSelectionList(){
    unset dirList
    buildListing
    out="$(termux-dialog checkbox -t "$(pwd)" -v "${dirList}")"
    getExCode "$out" "-1"
    getSelection "$out"
    selection="$(sed 's/^.//;s/.$//;s/^/ /' <<< "$selection")"
    IFS=','
    for kv in $selection
    do
        addFile="$(sed 's/^...//' <<< "$kv")"
        fileList="${fileList} ${addFile}"
    done
    unset IFS
    if [[ "$selection" == "" ]]
    then
        exit 0
    fi
}
buildArguments(){
    argList="$(sed 's/  */ /g' <<< "$encrPass $volSize $sfxArchive $headerEncr $solidArchive $compLevel $dictSize")"
}
archive(){
    unset encrPass
    unset volSize
    unset sfxArchive
    unset headerEncr
    unset solidArchive
    unset compLevel
    unset dictSize
    out="$(termux-dialog radio -t "Format:" \
    -v "zip,7z,tar,tar.gz,tar.bz2,tar.xz,tar.lz,tar.7z,cpio,cpio.gz,cpio.bz2,cpio.xz,cpio.lz,cpio.7z")"
    getExCode "$out" "-1"
    getSelection "$out"
    archiveType="$selection"
    case "$archiveType" in
        *"gz")
            opts="Set compression level"
        ;;
        *"bz2")
            opts="Set compression level"
        ;;
        *"xz")
            opts="Set compression level"
        ;;
        *"lz")
            opts="Set compression level,Set dictionary size"
        ;;
        *"7z")
            opts="Add password,Split into volumes,Create SFX,Header encryption,Solid archive,Set compression level,Set dictionary size"
        ;;
        "zip")
            opts="Add password,Split into volumes,Set compression level"
        ;;
    esac
    if [[ -n "$opts" ]]
    then
        out="$(termux-dialog checkbox -t "Options:" -v "$opts")"
        getExCode "$out" "-1"
        getSelection "$out"
    fi

    case "$selection" in
        *"Add password"*)
            while [[ ( ! "$encrPass" == "$confPass") || ( -z "$encrPass") ]]
            do
                out="$(termux-dialog text -p -i "Password" -t "Enter password:")"
                getExCode "$out" "-1"
                getSelection "$out"
                encrPass="$selection"
                out="$(termux-dialog text -p -i "Password" -t "Repeat:")"
                getExCode "$out" "-1"
                getSelection "$out"
                confPass="$selection"
                if [[ "$encrPass" == "confPass" ]]
                then
                    break
                else
                    echo "test"
                fi
            done
        ;;&
        *"Split into volumes"*)
            while [[ ! "$volSize" =~ ^[0-9]{1,5}$ ]]
            do
                out="$(termux-dialog text -n -t "Volume size:")"
                getExCode "$out" "-1"
                getSelection "$out"
                volSize="$selection"
                if [[ "$volSize" =~ ^[0-9]{1,5}$ ]]
                then
                    break
                else
                    echo "test"
                fi
            done
        ;;&
        *"Create SFX"*)
            sfxArchive="yes"
        ;;&
        *"Header encryption"*)
            headerEncr="yes"
        ;;&
        *"Solid archive"*)
            solidArchive="yes"
        ;;&
        *"Set compression level"*)
            out="$(termux-dialog counter -t "Compression level:" -r "0,6,9")"
            getExCode "$out" "-1"
            getSelection "$out"
            compLevel="$selection"
        ;;&
        *"Set dictionary size"*)
            out="$(termux-dialog spinner -t "Dictionary size:" -v "${dictSizes}")"
            getExCode "$out" "-1"
            getSelection "$out"
            dictSize="$selection"
        ;;
    esac
    addPath Compress
    while [[ ( -z "$filename" ) || ( -e "$(realpath "$filename")" ) ]]
    do
        out="$(termux-dialog text -t "Enter archive name:" -i "$(pwd | sed 's/.*\///').${archiveType}")"
        getExCode "$out" "-1"
        getSelection "$out"
        if [[ -z "$selection" ]]
        then
            filename="${additionalPath}/$(pwd | sed 's/.*\///').${archiveType}"
        else
            filename="${additionalPath}/$selection.${archiveType}"
        fi
        if [[ -e "$(realpath "$filename")" ]]
        then
            out="$(termux-dialog confirm -t "File already exists, overwrite?")"
            getExCode "$out" "0"
            getSelection "$out"
            if [[ "$selection" == "yes" ]]
            then
                break 1
            fi
        fi
    done
    notifId="${RANDOM}"
    termux-notification --content "Compressing..." --id "$notifId"
    case "$archiveType" in
    "zip")
        [[ -n "$encrPass" ]] && encrPass="-p${encrPass}"
        [[ -n "$volSize" ]] && volSize="-v${volSize}m"
        [[ -n "$compLevel" ]] && compLevel="-mx=${compLevel}"
        buildArguments
        zip -r $argList "$filename" $1
    ;;
    "7z")
        [[ -n "$encrPass" ]] && encrPass="-p${encrPass}"
        [[ -n "$volSize" ]] && volSize="-v${volSize}m"
        [[ -n "$sfxArchive" ]] && sfxArchive="-sfx"
        [[ -n "$headerEncr" ]] && headerEncr="-mhe=on"
        [[ -n "$solidArchive" ]] && solidArchive="-ms=on"
        [[ -n "$compLevel" ]] && compLevel="-mx=${compLevel}"
        [[ -n "$dictSize" ]] && dictSize="-md=${dictSize}"
        buildArguments
        7z a $argList "$filename" $1
    ;;
    "tar")
        tar -cf "$filename" $1
    ;;
    "tar.gz")
        [[ -n "$compLevel" ]] && compLevel="-${compLevel}"
        buildArguments
        tar -cf - $1 | gzip $argList - > "$filename"
    ;;
    "tar.bz2")
        [[ -n "$compLevel" ]] && compLevel="-${compLevel}"
        buildArguments
        tar -cf - $1 | bzip2 $argList - > "$filename"
    ;;
    "tar.xz")
        [[ -n "$compLevel" ]] && compLevel="-${compLevel}"
        buildArguments
        tar -cf - $1 | xz $argList > "$filename"
    ;;
    "tar.lz")
        [[ -n "$compLevel" ]] && compLevel="-${compLevel}"
        [[ -n "$dictSize" ]] && dictSize="--dictionary-size==${dictSize}M"
        buildArguments
        tar -cf - $1 | lzip $argList > "$filename"
    ;;
    "tar.7z")
        [[ -n "$encrPass" ]] && encrPass="-p${encrPass}"
        [[ -n "$volSize" ]] && volSize="-v${volSize}m"
        [[ -n "$sfxArchive" ]] && sfxArchive="-sfx"
        [[ -n "$headerEncr" ]] && headerEncr="-mhe=on"
        [[ -n "$solidArchive" ]] && solidArchive="-ms=on"
        [[ -n "$compLevel" ]] && compLevel="-mx=${compLevel}"
        [[ -n "$dictSize" ]] && dictSize="-md=${dictSize}"
        buildArguments
        tar cf - $1 | 7z a -si $argList "$filename"
    ;;
    "cpio")
        find $1 -print -depth | cpio -ov > "$filename"
    ;;
    "cpio.gz")
        [[ -n "$compLevel" ]] && compLevel="-${compLevel}"
        buildArguments
        find $1 -print -depth | cpio -ov | gzip $argList - > "$filename"
    ;;
    "cpio.bz2")
        [[ -n "$compLevel" ]] && compLevel="-${compLevel}"
        buildArguments
        find $1 -print -depth | cpio -ov | bzip2 $argList - > "$filename"
    ;;
    "cpio.xz")
        [[ -n "$compLevel" ]] && compLevel="-${compLevel}"
        buildArguments
        find $1 -print -depth | cpio -ov | xz $argList > "$filename"
    ;;
    "cpio.lz")
        [[ -n "$compLevel" ]] && compLevel="-${compLevel}"
        [[ -n "$dictSize" ]] && dictSize="--dictionary-size==${dictSize}M"
        buildArguments
        find $1 -print -depth | cpio -ov | lzip $argList > "$filename"
    ;;
    "cpio.7z")
        [[ -n "$encrPass" ]] && encrPass="-p${encrPass}"
        [[ -n "$volSize" ]] && volSize="-v${volSize}m"
        [[ -n "$sfxArchive" ]] && sfxArchive="-sfx"
        [[ -n "$headerEncr" ]] && headerEncr="-mhe=on"
        [[ -n "$solidArchive" ]] && solidArchive="-ms=on"
        [[ -n "$compLevel" ]] && compLevel="-mx=${compLevel}"
        [[ -n "$dictSize" ]] && dictSize="-md=${dictSize}"
        buildArguments
        find $1 -print -depth | cpio -ov | 7z a -si $argList "$filename"
    ;;
    esac
    termux-notification-remove "$notifId"
}
calculateChecksum(){
    checkSum="$($2 "$1" | awk -F ' ' '{print $1}')"
    clipboardSum="$(termux-clipboard-get)"
    if [[ "$checkSum" == "$clipboardSum" ]]
    then
        compareResult="Checksums are matching."
    else
        compareResult="Checksums are NOT matching."
    fi
    out="$(termux-dialog confirm -i "Checksum:${checkSum} Clipboard:${clipboardSum} ${compareResult}\
    Press "Yes" to copy checksum to clipboard.")"
    getSelection "$out"
    if [[ "$selection" == "yes" ]]
    then
        termux-clipboard-set "$checkSum"
    fi
}
addPath(){
    workingDir="$(pwd)"
    while [[ true ]]
    do
        unset dirList
        buildListing dirs
        out="$(termux-dialog radio -t "$(pwd)" -v "${actionIcon} "$1" here,${upDirIcon} Go to parent directory,${dirList}")"
        getSelection "$out"
        getExCode "$out" "-1"
        selection="$(sed 's/^..//' <<< "$selection")"
        if [[ "$selection" == ""$1" here" && ! -e "Use this dir" ]]
        then
            additionalPath="$(pwd)"
            break 1
        elif [[ "$selection" == "Go to parent directory" && ! -e "Go to parent directory" ]]
        then
            cd ..
        elif [[ -d "$(realpath "${selection}")" ]]
        then
            cd "$selection"
        fi
    done
    cd "$workingDir"
}
extract(){
    if [[ "$1" =~ (${archiveTypes})$ ]]
    then
        opts="Extract,Rename,Calculate md5,Calculate sha256,Calculate sha512"
    else
        opts="Rename,Calculate md5,Calculate sha256,Calculate sha512"
    fi
    out="$(termux-dialog radio -v "$opts" -t "Select operation:")"
    getExCode "$out" "-1"
    getSelection "$out"
    case "$selection" in
        "Extract")
            addPath "Extract"
            folderName="${additionalPath}/$(sed 's/\..*$//' <<< "$1")"
            realFile="$(realpath $1)"
            mkdir "$folderName"
            cd "$folderName"
            notifId="$(cat /proc/sys/kernel/random/uuid)"
            termux-notification --content "Extracting..." --id "$notifId"
            case "$1" in
            *".zip"|*".jar"|*".apk")
                7z e "$realFile"
            ;;
            *".tar")
                tar -xf "$realFile"
            ;;
            *".cpio")
                cpio -idv < "$realFile"
            ;;
            *".tar.7z"|*".t7z")
                7z e "$realFile" -so | tar -x
            ;;
            *".cpio.7z")
                7z e "$realFile" -so | cpio -idv
            ;;
            *".7z")
                7z e "$realFile"
            ;;
            *".tar.gz"|*".tgz")
                tar -xvzf "$realFile"
            ;;
            *".tar.bz2"|*".tbz"|*".tbz2")
                tar -jxf "$realFile"
            ;;
            *".tar.xz"|*".txz")
                tar -xJf "$realFile"
            ;;
            *".tar.lz"|*".tlz")
                tar --lzip -xvf "$realFile"
            ;;
            *".cpio.gz")
                gzip -dc "$realFile" | cpio -idmv
            ;;
            *".cpio.bz2")
                bzip2 -dc "$realFile" | cpio -idmv
            ;;
            *".cpio.xz")
                xz -dc "$realFile" | cpio -idmv
            ;;
            *".cpio.lz")
                lzip -dc "$realFile" | cpio -idmv
            ;;
            esac
            termux-notification-remove "$notifId"
            cd -
        ;;
        "Rename")
            out="$(termux-dialog text -t "Rename:" -i "$1")"
            getExCode "$out" "-1"
            getSelection "$out"
            if [[ $(ls "$selection") ]]
            then
                out="$(termux-dialog confirm -t "File already exists" -i "Overwrite?")"
                getSelection "$out"
                if [[ ! "$selection" == "yes" ]]
                then
                    break 2
                fi
            fi
            mv "$1" "$selection"
        ;;
        "Calculate md5")
            calculateChecksum "$1" md5sum
        ;;
        "Calculate sha256")
            calculateChecksum "$1" sha256sum
        ;;
        "Calculate sha512")
            calculateChecksum "$1" sha512sum
        ;;
    esac
}

########################
#Main section
########################

for pkg in $binList
do
    if [[ ! -f "/data/data/com.termux/files/usr/bin/$pkg" ]]
    then
        echo "Some packages are missing in your termux installation. Install them now? (y/n):"
        read inp
        if [[ "$inp" =~ [Yy] ]]
        then
            apt install -y $packageList
        else
            exit 0
        fi
    fi
done

cd ~/storage/shared

while [[ true ]]
do
    unset dirList
    buildListing
    out="$(termux-dialog radio -t "$(pwd)" -v "${actionIcon} Use this dir,${upDirIcon} Go to parent directory,${dirList}")"
    getSelection "$out"
    getExCode "$out" "-1"
    selection="$(sed 's/^..//' <<< "$selection")"
    if [[ "$selection" == "Use this dir" && ! -e "Use this dir" ]]
    then
        buildSelectionList
        archive "$fileList"
    elif [[ "$selection" == "Go to parent directory" && ! -e "Go to parent directory" ]]
    then
        cd ..
    elif [[ -d "$(realpath "${selection}")" ]]
    then
        cd "$selection"
    elif [[ -f "$(realpath "${selection}")" ]]
    then
        extract "$selection"
    fi
done
